# Generated by Django 4.2 on 2023-05-02 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fitness_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="programs",
            name="trainer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="fitness_app.trainers",
            ),
            preserve_default=False,
        ),
    ]
