# Generated by Django 4.2 on 2023-05-02 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fitness_app", "0002_programs_trainer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classes",
            name="program",
        ),
        migrations.DeleteModel(
            name="Programs",
        ),
    ]
